### ISSUE TITLE
What does -l system do?

### ISSUE THREAD

**Issue by Gapoly** [vinceliuice/Elegant-grub2-themes#13]
I wanted to put another logo on my grub2 but couldn't because I couldn't find any when I did -l. I did -l system and I got the default logo, which is the mountain.

What does -l system do?
What logo is there?
Can I put my own? (If yes, how?)

**Comment by vinceliuice** [comment]
`-l default` is mountain logo

**Comment by vinceliuice** [comment]
`-l system` is your OS system logo

**Comment by Gapoly** [comment]
I did a ```sudo ./install.sh -l system``` but I got the mountain logo

**Comment by vinceliuice** [comment]
What's your system verison ? if it's not supported then it'll use default logo

**Comment by Gapoly** [comment]
I'm on Arch Linux

**Comment by vinceliuice** [comment]
Could you Run: `lsb_release -i` and tell me the output ?  I need your system ID to correct the icon name

**Comment by Gapoly** [comment]
> lsb_release -i

```Distributor ID: Arch```

**Comment by Gapoly** [comment]
👍️👍️
