### ISSUE TITLE
opensuse.png already exists

### ISSUE THREAD

**Issue by Farlavendi** [vinceliuice/Elegant-grub2-themes#7]
While running install command: `sudo ./install.sh -b -t mountain -p sharp -i left -c dark -s 1080p` 
I get this error: `cp: cannot create regular file '/boot/grub/themes/Elegant-mountain-sharp-left-dark/icons/opensuse.png': File exists`
This happens somewhere in the process of installation and deleting the folder and rerunning the install script doesn't fix anything.
![image](https://github.com/user-attachments/assets/2019ad4f-1a6b-4a44-8a6c-543ba1f720bb)

P.S. Tried changing flags and the sequence of parameters but the issue unfortunately still takes place.
Previously I installed regular grub2 themes and everything was alright.

**Comment by vinceliuice** [comment]
![Screenshot From 2024-11-14 15-06-56](https://github.com/user-attachments/assets/8b56fc04-65b5-46c0-b5e0-ac97a8228d6d)

**Comment by vinceliuice** [comment]
What's your system version ?

**Comment by Farlavendi** [comment]
Arch Linux 
Kernel: Linux 6.11.6-arch1-1

**Comment by DenisBichuk** [comment]
For some reason installing the theme with dialog went smooth.
(I also remover previous theme string from grub config so it could also help)
But in the end everything works fine. 
Appreciate your work on themes. They are really cool.

**Comment by Farlavendi** [comment]
For some reason installing the theme with dialog went smooth.
P.S. Even after the reboot I tried to install another theme and the dialog process works, the basic one(with -flags) breaks
But in the end everything works fine.
Appreciate your work on themes. They are really cool.
